packages:
  - 'apps/*'
  - 'packages/*'

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - '@turntable/*'

confirmModulesPurge: false
injectWorkspacePackages: true

allowBuilds:
  '@prisma/engines': true
  '@scarf/scarf': false
  cpu-features: false
  esbuild: true
  msgpackr-extract: false
  prisma: true
  protobufjs: false
  ssh2: false
